package org.parcore.domain;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * PAR API
 * <p>
 * Action
 * <p>
 * Domain model for the action object (part of the BusinessRule Core Entity)
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
@SuppressWarnings("unused")
public class Action {

    @SerializedName("optionalInputProperties")
    private List<InputProperty> optionalInputProperties = null;

    @SerializedName("optionalInputFiles")
    private List<InputFile> optionalInputFiles = null;

    @SerializedName("outputPropertiesRetrieved")
    private List<OutputProperty> outputPropertiesRetrieved = null;

    @SerializedName("outputFilesRetrieved")
    private List<OutputFile> outputFilesRetrieved = null;

    @SerializedName("rawOutputsRetrieved")
    private List<OutputRaw> rawOutputsRetrieved = null;

    @SerializedName("preservationAction")
    private ParIdentifier preservationAction = null;

    @SerializedName("priority")
    private Integer priority = null;

    public void addOptionalInputPropertiesItem(InputProperty optionalInputPropertiesItem) {
        if (this.optionalInputProperties == null) {
            this.optionalInputProperties = new ArrayList<>();
        }
        this.optionalInputProperties.add(optionalInputPropertiesItem);
    }

    /**
     * Get optionalInputProperties
     *
     * @return optionalInputProperties
     **/
    @ApiModelProperty(value = "")
    public List<InputProperty> getOptionalInputProperties() {
        return optionalInputProperties;
    }

    public void setOptionalInputProperties(List<InputProperty> optionalInputProperties) {
        this.optionalInputProperties = optionalInputProperties;
    }

    public void addOptionalInputFilesItem(InputFile optionalInputFilesItem) {
        if (this.optionalInputFiles == null) {
            this.optionalInputFiles = new ArrayList<>();
        }
        this.optionalInputFiles.add(optionalInputFilesItem);
    }

    /**
     * Get optionalInputFiles
     *
     * @return optionalInputFiles
     **/
    @ApiModelProperty(value = "")
    public List<InputFile> getOptionalInputFiles() {
        return optionalInputFiles;
    }

    public void setOptionalInputFiles(List<InputFile> optionalInputFiles) {
        this.optionalInputFiles = optionalInputFiles;
    }

    public void addOutputPropertiesRetrievedItem(OutputProperty outputPropertiesRetrievedItem) {
        if (this.outputPropertiesRetrieved == null) {
            this.outputPropertiesRetrieved = new ArrayList<>();
        }
        this.outputPropertiesRetrieved.add(outputPropertiesRetrievedItem);
    }

    /**
     * Get outputPropertiesRetrieved
     *
     * @return outputPropertiesRetrieved
     **/
    @ApiModelProperty(value = "")
    public List<OutputProperty> getOutputPropertiesRetrieved() {
        return outputPropertiesRetrieved;
    }

    public void setOutputPropertiesRetrieved(List<OutputProperty> outputPropertiesRetrieved) {
        this.outputPropertiesRetrieved = outputPropertiesRetrieved;
    }

    public void addOutputFilesRetrievedItem(OutputFile outputFilesRetrievedItem) {
        if (this.outputFilesRetrieved == null) {
            this.outputFilesRetrieved = new ArrayList<>();
        }
        this.outputFilesRetrieved.add(outputFilesRetrievedItem);
    }

    /**
     * Get outputFilesRetrieved
     *
     * @return outputFilesRetrieved
     **/
    @ApiModelProperty(value = "")
    public List<OutputFile> getOutputFilesRetrieved() {
        return outputFilesRetrieved;
    }

    public void setOutputFilesRetrieved(List<OutputFile> outputFilesRetrieved) {
        this.outputFilesRetrieved = outputFilesRetrieved;
    }

    public void addRawOutputsRetrievedItem(OutputRaw rawOutputsRetrievedItem) {
        if (this.rawOutputsRetrieved == null) {
            this.rawOutputsRetrieved = new ArrayList<>();
        }
        this.rawOutputsRetrieved.add(rawOutputsRetrievedItem);
    }

    /**
     * Get rawOutputsRetrieved
     *
     * @return rawOutputsRetrieved
     **/
    @ApiModelProperty(value = "")
    public List<OutputRaw> getRawOutputsRetrieved() {
        return rawOutputsRetrieved;
    }

    public void setRawOutputsRetrieved(List<OutputRaw> rawOutputsRetrieved) {
        this.rawOutputsRetrieved = rawOutputsRetrieved;
    }

    /**
     * Get preservationAction
     *
     * @return preservationAction
     **/
    @ApiModelProperty(required = true, value = "")
    public ParIdentifier getPreservationAction() {
        return preservationAction;
    }

    public void setPreservationAction(ParIdentifier preservationAction) {
        this.preservationAction = preservationAction;
    }

    /**
     * Get priority
     *
     * @return priority
     **/
    @ApiModelProperty(value = "")
    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Action action = (Action) o;
        return Objects.equals(this.optionalInputProperties, action.optionalInputProperties) &&
                Objects.equals(this.optionalInputFiles, action.optionalInputFiles) &&
                Objects.equals(this.outputPropertiesRetrieved, action.outputPropertiesRetrieved) &&
                Objects.equals(this.outputFilesRetrieved, action.outputFilesRetrieved) &&
                Objects.equals(this.rawOutputsRetrieved, action.rawOutputsRetrieved) &&
                Objects.equals(this.preservationAction, action.preservationAction) &&
                Objects.equals(this.priority, action.priority);
    }

    @Override
    public int hashCode() {
        return Objects.hash(optionalInputProperties, optionalInputFiles, outputPropertiesRetrieved, outputFilesRetrieved, rawOutputsRetrieved, preservationAction, priority);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Action {\n");

        sb.append("    optionalInputProperties: ").append(toIndentedString(optionalInputProperties)).append("\n");
        sb.append("    optionalInputFiles: ").append(toIndentedString(optionalInputFiles)).append("\n");
        sb.append("    outputPropertiesRetrieved: ").append(toIndentedString(outputPropertiesRetrieved)).append("\n");
        sb.append("    outputFilesRetrieved: ").append(toIndentedString(outputFilesRetrieved)).append("\n");
        sb.append("    rawOutputsRetrieved: ").append(toIndentedString(rawOutputsRetrieved)).append("\n");
        sb.append("    preservationAction: ").append(toIndentedString(preservationAction)).append("\n");
        sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
