package org.parcore.domain;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * PAR API
 * <p>
 * AuthorInformation
 * <p>
 * Domain model for the AuthorInformation object (part of the FileFormat Core Entity)
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
public class AuthorInformation {
    @SerializedName("authorId")
    private String authorId = null;

    @SerializedName("authorIdNamespace")
    private String authorIdNamespace = null;

    @SerializedName("authorName")
    private String authorName = null;

    @SerializedName("organisationName")
    private String organisationName = null;

    @SerializedName("authorCompoundName")
    private String authorCompoundName = null;

    public AuthorInformation authorId(String authorId) {
        this.authorId = authorId;
        return this;
    }

    /**
     * Get authorId
     *
     * @return authorId
     **/
    @ApiModelProperty(required = true, value = "")
    public String getAuthorId() {
        return authorId;
    }

    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    public AuthorInformation authorIdNamespace(String authorIdNamespace) {
        this.authorIdNamespace = authorIdNamespace;
        return this;
    }

    /**
     * Get authorIdNamespace
     *
     * @return authorIdNamespace
     **/
    @ApiModelProperty(required = true, value = "")
    public String getAuthorIdNamespace() {
        return authorIdNamespace;
    }

    public void setAuthorIdNamespace(String authorIdNamespace) {
        this.authorIdNamespace = authorIdNamespace;
    }

    public AuthorInformation authorName(String authorName) {
        this.authorName = authorName;
        return this;
    }

    /**
     * Get authorName
     *
     * @return authorName
     **/
    @ApiModelProperty(value = "")
    public String getAuthorName() {
        return authorName;
    }

    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    public AuthorInformation organisationName(String organisationName) {
        this.organisationName = organisationName;
        return this;
    }

    /**
     * Get organisationName
     *
     * @return organisationName
     **/
    @ApiModelProperty(value = "")
    public String getOrganisationName() {
        return organisationName;
    }

    public void setOrganisationName(String organisationName) {
        this.organisationName = organisationName;
    }

    public AuthorInformation authorCompoundName(String authorCompoundName) {
        this.authorCompoundName = authorCompoundName;
        return this;
    }

    /**
     * Get authorCompoundName
     *
     * @return authorCompoundName
     **/
    @ApiModelProperty(value = "")
    public String getAuthorCompoundName() {
        return authorCompoundName;
    }

    public void setAuthorCompoundName(String authorCompoundName) {
        this.authorCompoundName = authorCompoundName;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthorInformation authorInformation = (AuthorInformation) o;
        return Objects.equals(this.authorId, authorInformation.authorId) &&
                Objects.equals(this.authorIdNamespace, authorInformation.authorIdNamespace) &&
                Objects.equals(this.authorName, authorInformation.authorName) &&
                Objects.equals(this.organisationName, authorInformation.organisationName) &&
                Objects.equals(this.authorCompoundName, authorInformation.authorCompoundName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(authorId, authorIdNamespace, authorName, organisationName, authorCompoundName);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AuthorInformation {\n");

        sb.append("    authorId: ").append(toIndentedString(authorId)).append("\n");
        sb.append("    authorIdNamespace: ").append(toIndentedString(authorIdNamespace)).append("\n");
        sb.append("    authorName: ").append(toIndentedString(authorName)).append("\n");
        sb.append("    organisationName: ").append(toIndentedString(organisationName)).append("\n");
        sb.append("    authorCompoundName: ").append(toIndentedString(authorCompoundName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

