package org.parcore.domain;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * PAR API
 * <p>
 * IdentifierInformation
 * <p>
 * Domain model for the IdentifierInformation object (part of the FileFormat Core Entity)
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
public class IdentifierInformation {
    @SerializedName("identifier")
    private String identifier = null;

    @SerializedName("identifierType")
    private String identifierType = null;

    public IdentifierInformation identifier(String identifier) {
        this.identifier = identifier;
        return this;
    }

    /**
     * Get identifier
     *
     * @return identifier
     **/
    @ApiModelProperty(required = true, value = "")
    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public IdentifierInformation identifierType(String identifierType) {
        this.identifierType = identifierType;
        return this;
    }

    /**
     * Get identifierType
     *
     * @return identifierType
     **/
    @ApiModelProperty(required = true, value = "")
    public String getIdentifierType() {
        return identifierType;
    }

    public void setIdentifierType(String identifierType) {
        this.identifierType = identifierType;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        IdentifierInformation identifierInformation = (IdentifierInformation) o;
        return Objects.equals(this.identifier, identifierInformation.identifier) &&
                Objects.equals(this.identifierType, identifierInformation.identifierType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(identifier, identifierType);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class IdentifierInformation {\n");

        sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
        sb.append("    identifierType: ").append(toIndentedString(identifierType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

