package org.parcore.domain;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * PAR API
 * <p>
 * OutputFile
 * <p>
 * Domain model for the OutputFile object (part of the PreservationAction Core Entity)
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
@ApiModel(description = "An output file from a preservation action")
@SuppressWarnings("unused")
public class OutputFile {
    @SerializedName("description")
    private String description = null;

    @SerializedName("file")
    private ParFile file = null;

    @SerializedName("name")
    private String name = null;

    /**
     * Get description
     *
     * @return description
     **/
    @ApiModelProperty(required = true, value = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Get file
     *
     * @return file
     **/
    @ApiModelProperty(required = true, value = "")
    public ParFile getFile() {
        return file;
    }

    public void setFile(ParFile file) {
        this.file = file;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @ApiModelProperty(required = true, value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OutputFile outputFile = (OutputFile) o;
        return Objects.equals(this.description, outputFile.description) &&
                Objects.equals(this.file, outputFile.file) &&
                Objects.equals(this.name, outputFile.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(description, file, name);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OutputFile {\n");

        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    file: ").append(toIndentedString(file)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
