package org.parcore.domain;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

import org.threeten.bp.OffsetDateTime;

/**
 * PAR API
 * <p>
 * PreservationAction
 * <p>
 * Domain model for the PreservationAction Core Entity
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
@SuppressWarnings("unused")
public class PreservationAction {

    @SerializedName("constraints")
    private List<PreservationActionConstraints> constraints = null;

    @SerializedName("description")
    private String description = null;

    @SerializedName("example")
    private String example = null;

    @SerializedName("id")
    private ParIdentifier id = null;

    @SerializedName("inputFiles")
    private List<InputFile> inputFiles = null;

    @SerializedName("inputProperties")
    private List<InputProperty> inputProperties = null;

    @SerializedName("localLastModifiedDate")
    private OffsetDateTime localLastModifiedDate = null;

    @SerializedName("outputFiles")
    private List<OutputFile> outputFiles = null;

    @SerializedName("outputProperties")
    private List<OutputProperty> outputProperties = null;

    @SerializedName("rawOutputs")
    private List<OutputRaw> rawOutputs = null;

    @SerializedName("tool")
    private Tool tool = null;

    @SerializedName("type")
    private PreservationActionType type = null;

    public void addConstraintsItem(PreservationActionConstraints constraintsItem) {
        if (this.constraints == null) {
            this.constraints = new ArrayList<>();
        }
        this.constraints.add(constraintsItem);
    }

    /**
     * Get constraints
     *
     * @return constraints
     **/
    @ApiModelProperty(value = "")
    public List<PreservationActionConstraints> getConstraints() {
        return constraints;
    }

    public void setConstraints(List<PreservationActionConstraints> constraints) {
        this.constraints = constraints;
    }

    /**
     * Get description
     *
     * @return description
     **/
    @ApiModelProperty(required = true, value = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Get example
     *
     * @return example
     **/
    @ApiModelProperty(value = "")
    public String getExample() {
        return example;
    }

    public void setExample(String example) {
        this.example = example;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "")
    public ParIdentifier getId() {
        return id;
    }

    public void setId(ParIdentifier id) {
        this.id = id;
    }

    public void addInputFilesItem(InputFile inputFile) {
        this.inputFiles.add(inputFile);
    }

    /**
     * Get inputFiles
     *
     * @return inputFiles
     */
    @ApiModelProperty(value = "")
    public List<InputFile> getInputFiles() {
        return inputFiles;
    }

    public void setInputFiles(List<InputFile> inputFiles) {
        this.inputFiles = inputFiles;
    }

    public void addInputPropertiesItem(InputProperty inputProperty) {
        this.inputProperties.add(inputProperty);
    }

    /**
     * Get inputProperties
     *
     * @return inputProperties
     */
    @ApiModelProperty(value = "")
    public List<InputProperty> getInputProperties() {
        return inputProperties;
    }

    public void setInputProperties(List<InputProperty> inputProperties) {
        this.inputProperties = inputProperties;
    }

    /**
     * Get localLastModifiedDate
     *
     * @return localLastModifiedDate
     **/
    @ApiModelProperty(value = "")
    public OffsetDateTime getLocalLastModifiedDate() {
        return localLastModifiedDate;
    }

    public void setLocalLastModifiedDate(OffsetDateTime localLastModifiedDate) {
        this.localLastModifiedDate = localLastModifiedDate;
    }

    public void addOutputFilesItem(OutputFile outputFile) {
        this.outputFiles.add(outputFile);
    }

    /**
     * Get outputFiles
     *
     * @return outputFiles
     */
    @ApiModelProperty(value = "")
    public List<OutputFile> getOutputFiles() {
        return outputFiles;
    }

    public void setOutputFiles(List<OutputFile> outputFiles) {
        this.outputFiles = outputFiles;
    }

    public void addOutputPropertiesItem(OutputProperty outputProperty) {
        this.outputProperties.add(outputProperty);
    }

    /**
     * Get outputProperties
     *
     * @return outputProperties
     */
    @ApiModelProperty(value = "")
    public List<OutputProperty> getOutputProperties() {
        return outputProperties;
    }

    public void setOutputProperties(List<OutputProperty> outputProperties) {
        this.outputProperties = outputProperties;
    }

    public void addRawOutputsItem(OutputRaw rawOutput) {
        this.rawOutputs.add(rawOutput);
    }

    /**
     * Get rawOutputs
     *
     * @return rawOutputs
     */
    @ApiModelProperty(value = "")
    public List<OutputRaw> getRawOutputs() {
        return rawOutputs;
    }

    public void setRawOutputs(List<OutputRaw> rawOutputs) {
        this.rawOutputs = rawOutputs;
    }

    /**
     * Get tool
     *
     * @return tool
     **/
    @ApiModelProperty(required = true, value = "")
    public Tool getTool() {
        return tool;
    }

    public void setTool(Tool tool) {
        this.tool = tool;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @ApiModelProperty(required = true, value = "")
    public PreservationActionType getType() {
        return type;
    }

    public void setType(PreservationActionType type) {
        this.type = type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PreservationAction preservationAction = (PreservationAction) o;
        return Objects.equals(this.constraints, preservationAction.constraints) &&
                Objects.equals(this.description, preservationAction.description) &&
                Objects.equals(this.example, preservationAction.example) &&
                Objects.equals(this.id, preservationAction.id) &&
                Objects.equals(this.inputFiles, preservationAction.inputFiles) &&
                Objects.equals(this.inputProperties, preservationAction.inputProperties) &&
                Objects.equals(this.localLastModifiedDate, preservationAction.localLastModifiedDate) &&
                Objects.equals(this.outputFiles, preservationAction.outputFiles) &&
                Objects.equals(this.outputProperties, preservationAction.outputProperties) &&
                Objects.equals(this.rawOutputs, preservationAction.rawOutputs) &&
                Objects.equals(this.tool, preservationAction.tool) &&
                Objects.equals(this.type, preservationAction.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(constraints, description, example, id, inputFiles, inputProperties, localLastModifiedDate, outputFiles, outputProperties, rawOutputs, tool, type);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PreservationAction {\n");

        sb.append("    constraints: ").append(toIndentedString(constraints)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    example: ").append(toIndentedString(example)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    inputFiles: ").append(toIndentedString(inputFiles)).append("\n");
        sb.append("    inputProperties: ").append(toIndentedString(inputProperties)).append("\n");
        sb.append("    localLastModifiedDate: ").append(toIndentedString(localLastModifiedDate)).append("\n");
        sb.append("    outputFiles: ").append(toIndentedString(outputFiles)).append("\n");
        sb.append("    outputProperties: ").append(toIndentedString(outputProperties)).append("\n");
        sb.append("    rawOutputs: ").append(toIndentedString(rawOutputs)).append("\n");
        sb.append("    tool: ").append(toIndentedString(tool)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
