package org.parcore.domain;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * PAR API
 * <p>
 * PreservationActionTypes
 * <p>
 * Domain model for a list of PreservationActionType Core entity objects, as returned by the API
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
@ApiModel(description = "A list of preservation action types")
public class PreservationActionTypes {
    @SerializedName("preservationActionTypes")
    private List<PreservationActionType> preservationActionTypes = null;

    public PreservationActionTypes preservationActionTypes(List<PreservationActionType> preservationActionTypes) {
        this.preservationActionTypes = preservationActionTypes;
        return this;
    }

    public PreservationActionTypes addPreservationActionTypesItem(PreservationActionType preservationActionTypesItem) {
        if (this.preservationActionTypes == null) {
            this.preservationActionTypes = new ArrayList<>();
        }
        this.preservationActionTypes.add(preservationActionTypesItem);
        return this;
    }

    /**
     * Get preservationActionTypes
     *
     * @return preservationActionTypes
     **/
    @ApiModelProperty(value = "")
    public List<PreservationActionType> getPreservationActionTypes() {
        return preservationActionTypes;
    }

    public void setPreservationActionTypes(List<PreservationActionType> preservationActionTypes) {
        this.preservationActionTypes = preservationActionTypes;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PreservationActionTypes preservationActionTypes = (PreservationActionTypes) o;
        return Objects.equals(this.preservationActionTypes, preservationActionTypes.preservationActionTypes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(preservationActionTypes);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PreservationActionTypes {\n");

        sb.append("    preservationActionTypes: ").append(toIndentedString(preservationActionTypes)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

