package org.parcore.domain;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * PAR API
 * <p>
 * PublisherInformation
 * <p>
 * Domain model for the PublisherInformation object (part of the FileFormat Core Entity)
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
public class PublisherInformation {
    @SerializedName("publisherId")
    private String publisherId = null;

    @SerializedName("publisherIdNamespace")
    private String publisherIdNamespace = null;

    @SerializedName("publisherName")
    private String publisherName = null;

    @SerializedName("organisationName")
    private String organisationName = null;

    @SerializedName("publisherCompoundName")
    private String publisherCompoundName = null;

    public PublisherInformation publisherId(String publisherId) {
        this.publisherId = publisherId;
        return this;
    }

    /**
     * Get publisherId
     *
     * @return publisherId
     **/
    @ApiModelProperty(required = true, value = "")
    public String getPublisherId() {
        return publisherId;
    }

    public void setPublisherId(String publisherId) {
        this.publisherId = publisherId;
    }

    public PublisherInformation publisherIdNamespace(String publisherIdNamespace) {
        this.publisherIdNamespace = publisherIdNamespace;
        return this;
    }

    /**
     * Get publisherIdNamespace
     *
     * @return publisherIdNamespace
     **/
    @ApiModelProperty(required = true, value = "")
    public String getPublisherIdNamespace() {
        return publisherIdNamespace;
    }

    public void setPublisherIdNamespace(String publisherIdNamespace) {
        this.publisherIdNamespace = publisherIdNamespace;
    }

    public PublisherInformation publisherName(String publisherName) {
        this.publisherName = publisherName;
        return this;
    }

    /**
     * Get publisherName
     *
     * @return publisherName
     **/
    @ApiModelProperty(value = "")
    public String getPublisherName() {
        return publisherName;
    }

    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName;
    }

    public PublisherInformation organisationName(String organisationName) {
        this.organisationName = organisationName;
        return this;
    }

    /**
     * Get organisationName
     *
     * @return organisationName
     **/
    @ApiModelProperty(value = "")
    public String getOrganisationName() {
        return organisationName;
    }

    public void setOrganisationName(String organisationName) {
        this.organisationName = organisationName;
    }

    public PublisherInformation publisherCompoundName(String publisherCompoundName) {
        this.publisherCompoundName = publisherCompoundName;
        return this;
    }

    /**
     * Get publisherCompoundName
     *
     * @return publisherCompoundName
     **/
    @ApiModelProperty(value = "")
    public String getPublisherCompoundName() {
        return publisherCompoundName;
    }

    public void setPublisherCompoundName(String publisherCompoundName) {
        this.publisherCompoundName = publisherCompoundName;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PublisherInformation publisherInformation = (PublisherInformation) o;
        return Objects.equals(this.publisherId, publisherInformation.publisherId) &&
                Objects.equals(this.publisherIdNamespace, publisherInformation.publisherIdNamespace) &&
                Objects.equals(this.publisherName, publisherInformation.publisherName) &&
                Objects.equals(this.organisationName, publisherInformation.organisationName) &&
                Objects.equals(this.publisherCompoundName, publisherInformation.publisherCompoundName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(publisherId, publisherIdNamespace, publisherName, organisationName, publisherCompoundName);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PublisherInformation {\n");

        sb.append("    publisherId: ").append(toIndentedString(publisherId)).append("\n");
        sb.append("    publisherIdNamespace: ").append(toIndentedString(publisherIdNamespace)).append("\n");
        sb.append("    publisherName: ").append(toIndentedString(publisherName)).append("\n");
        sb.append("    organisationName: ").append(toIndentedString(organisationName)).append("\n");
        sb.append("    publisherCompoundName: ").append(toIndentedString(publisherCompoundName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

