package org.parcore.api.client.utilities;

import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * PAR API
 * <p>
 * ApiResponse
 * <p>
 * Typed response from the API, includes the status code, response headers and Typed response body
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
public class ApiResponse<T> {
    final private int statusCode;
    final private Map<String, List<String>> headers;
    final private T data;

    /**
     * Constructor with no response body
     *
     * @param statusCode The status code of HTTP response
     * @param headers    The headers of HTTP response
     */
    public ApiResponse(int statusCode, Map<String, List<String>> headers) {
        this(statusCode, headers, null);
    }

    /**
     * Constructor with all data
     *
     * @param statusCode The status code of HTTP response
     * @param headers    The headers of HTTP response
     * @param data       The object deserialized from response bod
     */
    public ApiResponse(int statusCode, Map<String, List<String>> headers, T data) {
        this.statusCode = statusCode;
        this.headers = Collections.unmodifiableMap(headers);
        this.data = data;
    }

    public int getStatusCode() {
        return statusCode;
    }

    public Map<String, List<String>> getHeaders() {
        return headers;
    }

    public T getData() {
        return data;
    }
}
