package org.parcore.api.client.utilities;

/**
 * PAR API
 * <p>
 * ClientFactor
 * <p>
 * Factory class for getting ApiClients in various configurations
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
public class ClientFactory {

    //TODO: Add some standard configs

    private static ApiClient defaultApiClient = new ApiClient();

    /**
     * Get the default API client, which would be used when creating API
     * instances without providing an API client.
     *
     * @return Default API client
     */
    public static ApiClient getDefaultApiClient() {
        return defaultApiClient;
    }

}
