package org.parcore.api.client.utilities;

/**
 * PAR API
 * <p>
 * Pair
 * <p>
 * Generic Key-Value pair
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
public class Pair {
    private String name = "";
    private String value = "";

    public Pair(String name, String value) {
        setName(name);
        setValue(value);
    }

    private void setName(String name) {
        if (isInvalidString(name)) throw new IllegalArgumentException("Key must be a valid non-empty string");
        this.name = name;
    }

    private void setValue(String value) {
        if (isInvalidString(value)) throw new IllegalArgumentException("Value must be a valid non-empty string");
        this.value = value;
    }

    public String getName() {
        return this.name;
    }

    public String getValue() {
        return this.value;
    }

    private boolean isInvalidString(String arg) {
        if (arg == null) return true;
        return arg.trim().isEmpty();
    }
}
