package org.parcore.api.client.auth;

import org.parcore.api.client.utilities.Pair;

import java.util.Map;
import java.util.List;

/**
 * PAR API
 * <p>
 * Authentication Interface
 * <p>
 * Generic interface for applying various authentication schemes to a request.
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
public interface Authentication {

    /**
     * Apply authentication settings to header and query params.
     *
     * @param queryParams  List of query parameters
     * @param headerParams Map of header parameters
     */
    void applyToParams(List<Pair> queryParams, Map<String, String> headerParams);
}
