package org.parcore.api.client.auth;

import org.parcore.api.client.utilities.Pair;

import com.squareup.okhttp.Credentials;

import java.util.Map;
import java.util.List;

/**
 * PAR API
 * <p>
 * HttpBasicAuth
 * <p>
 * Implementation of the Authentication interface to append a HTTP Basic Auth header to the header parameters.
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
public class HttpBasicAuth implements Authentication {
    private String username;
    private String password;

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams) {
        if (username == null && password == null) {
            return;
        }
        headerParams.put("Authorization", Credentials.basic(
                username == null ? "" : username,
                password == null ? "" : password));
    }
}
