package org.parcore.api.client.auth;

/**
 * PAR API
 * <p>
 * OAuthFlow
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
public enum OAuthFlow {
    accessCode, implicit, password, application
}
