package org.parcore.api.client.auth;

import org.parcore.api.client.utilities.Pair;

import java.util.Map;
import java.util.List;

/**
 * PAR API
 * <p>
 * OAuth
 * <p>
 * Implementation of the Authentication interface to append an OAuth token to the header parameters.
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
public class OAuth implements Authentication {
    private String accessToken;

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    @Override
    public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams) {
        if (accessToken != null) {
            headerParams.put("Authorization", "Bearer " + accessToken);
        }
    }
}
