package org.parcore.api.client.endpoints;

import org.parcore.api.client.async.ApiCallback;
import org.parcore.api.client.utilities.ApiException;
import org.parcore.api.client.utilities.ApiResponse;
import org.parcore.domain.PreservationActionType;
import org.parcore.domain.PreservationActionTypes;

/**
 * PAR API
 * <p>
 * PreservationActionTypesApi
 * <p>
 * Client interface for the File Formats PAR Core Entity endpoint
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * This class is based on code auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 */
public interface PreservationActionTypesApi {

    /**
     * Retrieve all preservation action types
     * Allow to retrieve the details of all the preservation action types
     *
     * @return PreservationActionTypes
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    PreservationActionTypes getPreservationActionTypes() throws ApiException;

    /**
     * Retrieve all preservation action types wrapped in an API Response so that the full context of the server response is available
     * Allow to retrieve the details of all the preservation action types
     *
     * @return ApiResponse&lt;PreservationActionTypes&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    ApiResponse<PreservationActionTypes> getPreservationActionTypesApiResponse() throws ApiException;

    /**
     * Retrieve all preservation action types (asynchronously)
     * Allow to retrieve the details of all the preservation action types
     *
     * @param callback The callback to be executed when the API call finishes
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    void getPreservationActionTypesAsync(ApiCallback<PreservationActionTypes> callback) throws ApiException;

    /**
     * Retrieve a preservation action type
     * Allow to retrieve the details of the specific preservation action type provided in the url.
     *
     * @param id Unique identifier for the preservation action type to retrieve. (required)
     * @return PreservationActionType
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    PreservationActionType getPreservationActionTypeById(String id) throws ApiException;

    /**
     * Retrieve a preservation action type wrapped in an API Response so that the full context of the server response is available
     * Allow to retrieve the details of the specific preservation action type provided in the url.
     *
     * @param id Unique identifier for the preservation action type to retrieve. (required)
     * @return ApiResponse&lt;PreservationActionType&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    ApiResponse<PreservationActionType> updatePreservationActionTypeByIdApiResponse(String id) throws ApiException;

    /**
     * Retrieve a preservation action type (asynchronously)
     * Allow to retrieve the details of the specific preservation action type provided in the url.
     *
     * @param id       Unique identifier for the preservation action type to retrieve. (required)
     * @param callback The callback to be executed when the API call finishes
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    void getPreservationActionTypeByIdAsync(String id, ApiCallback<PreservationActionType> callback) throws ApiException;

    /**
     * Update an existing preservation action type The newly updated PreservationActionType is return by the request.
     * Allow to apply the changes specified int the body to the preservation action type provided in the url.
     *
     * @param id   Unique identifier for the existing preservation action type to update (required)
     * @param data (required)
     * @return PreservationActionType
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    PreservationActionType updatePreservationActionType(String id, PreservationActionType data) throws ApiException;

    /**
     * Update an existing preservation action type. The newly updated PreservationActionType is returned by the request wrapped in an API Response so that the full context of the server response is available
     * Allow to apply the changes specified int the body to the preservation action type provided in the url.
     *
     * @param id   Unique identifier for the existing preservation action type to update (required)
     * @param data (required)
     * @return ApiResponse&lt;PreservationActionType&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    ApiResponse<PreservationActionType> updatePreservationActionTypeByIdApiResponse(String id, PreservationActionType data) throws ApiException;

    /**
     * Update an existing preservation action type (asynchronously)
     * Allow to apply the changes specified int the body to the preservation action type provided in the url.
     *
     * @param id       Unique identifier for the existing preservation action type to update (required)
     * @param data     (required)
     * @param callback The callback to be executed when the API call finishes
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    void updatePreservationActionTypeAsync(String id, PreservationActionType data, ApiCallback<PreservationActionType> callback) throws ApiException;

    /**
     * Create a new preservation action type. The newly created PreservationActionType is returned by the request.
     * Create a new preservation action type with the data provided in the body of the request.
     *
     * @param data (required)
     * @return PreservationActionType
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    PreservationActionType createPreservationActionType(PreservationActionType data) throws ApiException;

    /**
     * Create a new preservation action type. The newly created PreservationActionType is returned by the request wrapped in an API Response so that the full context of the server response is available
     * Create a new preservation action type with the data provided in the body of the request.
     *
     * @param data (required)
     * @return ApiResponse&lt;PreservationActionType&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    ApiResponse<PreservationActionType> createPreservationActionTypeApiResponse(PreservationActionType data) throws ApiException;

    /**
     * Create a new preservation action type (asynchronously)
     * Create a new preservation action type with the data provided in the body of the request.
     *
     * @param data     (required)
     * @param callback The callback to be executed when the API call finishes
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    void createPreservationActionTypeAsync(PreservationActionType data, ApiCallback<PreservationActionType> callback) throws ApiException;
}
